spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/api_filmes
    username: mariarita
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
