version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mariarita
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: api_filmes
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: .
    container_name: spring-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/api_filmes
      SPRING_DATASOURCE_USERNAME: mariarita
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
